### ISSUE TITLE
Always3interest Crash on start new world

### ISSUE THREAD

**Issue by DarkApocalypse** [Pholith/ONI-Mods#16] opened 2022-03-19 07:48 UTC
**Describe the bug**
I try to create a new game. after World Generation, it crash. 

**To Reproduce**
1)Click new game
2)Select Spaced out mod
3)No sweat difficulty
4)Generate game
5)TADA... Crash before see ingame

**Output_log.txt**
MissingMethodException: void WorldGenUtil.ShuffleSeeded<!0>(System.Collections.Generic.IList`1<!!0>,System.Random)

Always3Interests.TraitPatch.Prefix (MinionStartingStats __instance, System.Boolean is_starter_minion, System.Collections.Generic.List`1[T] disabled_chore_groups, System.String guaranteedAptitudeID) (at <e9e021eb132049f8b8881a72f855819a>:0)
(wrapper dynamic-method) MinionStartingStats.MinionStartingStats.GenerateTraits_Patch2(MinionStartingStats,bool,System.Collections.Generic.List`1<ChoreGroup>,string,string)
MinionStartingStats..ctor (System.Boolean is_starter_minion, System.String guaranteedAptitudeID, System.String guaranteedTraitID) (at <85e481f6108c44bab975e181863217ef>:0)
(wrapper dynamic-method) CharacterContainer.CharacterContainer.GenerateCharacter_Patch1(CharacterContainer,bool,string)
CharacterContainer+<DelayedGeneration>d__45.MoveNext () (at <85e481f6108c44bab975e181863217ef>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <9cfd92ef5d5d4d0d88cb0368b5619b29>:0)

Build: U41-498381-S

**Comment by Pholith** [comment] 2023-11-18 10:06
I can't reproduce the bug in new versions of the mod. I think I already fixed it, so I close the issue. Don't hesitate to reopen it if the crash is still there.

**Closed as completed by Pholith** 2023-11-18 10:06 UTC
Labels: Bug
